### ISSUE TITLE
basename function can't recognize Windows '\\' path on Android devices. 

### ISSUE THREAD

**Issue by FengChendian** [dart-lang/core#547]
I tested it on Android14.

```dart
print('**********************');
print(p.basename('E:\\agent_reply.wav'));
```
![image](https://github.com/user-attachments/assets/2970a5f7-5475-4d5a-a7ae-b42af20141c5)

**Comment by lrhn** [comment]
This does look like it's working as intended. 

The path package uses the local system's behavior unless you ask for a different behavior by creating a `Context`.
It's states in the first paragraph of https://pub.dev/documentation/path/latest/

**Comment by lrhn** [comment]
It only supports Windows paths *as default* on Windows platforms. The default is the behavior of native paths on the current platform.
On other platforms, you need to ask for Windows behavior by creating a `var paths = Context(style: Style.windows)` and using that for doing path operations.
That also means that on other platforms, a `//UNC/foo/bar` path is treated correctly according to the local platform behavior, without (possibly surprisingly) using Window behavior.

What you should do depends on which behavior you want. If you don't know which system a user provided path comes from, you probably need to do some kind of detection, otherwise you cannot treat it correctly.
Whether that is `.contains(r'\')` or something more intricate (since Windows paths can use `/` too, but `c:/foo/` is an absolute path on Windows, and `/foo/` is not, the opposite of what other systems would say.
